<a href="https://colab.research.google.com/github/neddy0318/neddy_space/blob/main/%EC%8B%A0%EC%8A%B9%ED%98%84_API_%EC%88%98%EC%A7%91_%EB%B6%80%EB%8F%99%EC%82%B0_%EB%8D%B0%EC%9D%B4%ED%84%B0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import requests
url = "http://www.naver.com"
requests.get(url)

#200이면 정상 응답 하는것
#404 등 4(클라이언트 오류)나 5(서버오류)으로 시작하면 X

In [ ]:
requests.__version__

'2.31.0'

In [7]:

import xml.etree.ElementTree as ET    #ET : xml 전처리해주는 도구
import pandas as pd

In [ ]:
import requests

url = 'http://openapi.seoul.go.kr:8088/sample/xml/tbLnOpendataRentV/1/5/'

requests.get(url).text

'<?xml version="1.0" encoding="UTF-8"?>\n<tbLnOpendataRentV>\n<list_total_count>5791017</list_total_count>\n<RESULT>\n<CODE>INFO-000</CODE>\n<MESSAGE>정상 처리되었습니다</MESSAGE>\n</RESULT>\n<row>\n<ACC_YEAR>2024</ACC_YEAR>\n<SGG_CD>11230</SGG_CD>\n<SGG_NM>동대문구</SGG_NM>\n<BJDONG_CD>10700</BJDONG_CD>\n<BJDONG_NM>청량리동</BJDONG_NM>\n<LAND_GBN>1</LAND_GBN>\n<LAND_GBN_NM>대지</LAND_GBN_NM>\n<BOBN>0235</BOBN>\n<BUBN>0006</BUBN>\n<FLR_NO>16</FLR_NO>\n<CNTRCT_DE>20240325</CNTRCT_DE>\n<RENT_GBN>월세</RENT_GBN>\n<RENT_AREA>20.92</RENT_AREA>\n<RENT_GTN>1000</RENT_GTN>\n<RENT_FEE>100</RENT_FEE>\n<BLDG_NM>힐스테이트 청량리역</BLDG_NM>\n<BUILD_YEAR>2023</BUILD_YEAR>\n<HOUSE_GBN_NM>오피스텔</HOUSE_GBN_NM>\n<CNTRCT_PRD>24.03~25.03</CNTRCT_PRD>\n<NEW_RON_SECD>신규</NEW_RON_SECD>\n<CNTRCT_UPDT_RQEST_AT/>\n<BEFORE_GRNTY_AMOUNT/>\n<BEFORE_MT_RENT_CHRGE/>\n</row>\n<row>\n<ACC_YEAR>2024</ACC_YEAR>\n<SGG_CD>11560</SGG_CD>\n<SGG_NM>영등포구</SGG_NM>\n<BJDONG_CD>10900</BJDONG_CD>\n<BJDONG_NM>영등포동8가</BJDONG_NM>\n<LAND_GBN>1</LAND_GBN>\n<LAND_GBN_NM>대지</LAND_GBN_NM>\n<BOBN>0065</BOBN>\n<BUBN>0001</BUBN>\n<FLR_NO>6</FLR_NO>\n<CNTRCT_DE>20240325</CNTRCT_DE>\n<RENT_GBN>전세</RENT_GBN>\n<RENT_AREA>17.58</RENT_AREA>\n<RENT_GTN>22000</RENT_GTN>\n<RENT_FEE>0</RENT_FEE>\n<BLDG_NM>엠캐슬150</BLDG_NM>\n<BUILD_YEAR>2024</BUILD_YEAR>\n<HOUSE_GBN_NM>오피스텔</HOUSE_GBN_NM>\n<CNTRCT_PRD>24.04~26.04</CNTRCT_PRD>\n<NEW_RON_SECD>신규</NEW_RON_SECD>\n<CNTRCT_UPDT_RQEST_AT/>\n<BEFORE_GRNTY_AMOUNT/>\n<BEFORE_MT_RENT_CHRGE/>\n</row>\n<row>\n<ACC_YEAR>2024</ACC_YEAR>\n<SGG_CD>11545</SGG_CD>\n<SGG_NM>금천구</SGG_NM>\n<BJDONG_CD>10200</BJDONG_CD>\n<BJDONG_NM>독산동</BJDONG_NM>\n<LAND_GBN>1</LAND_GBN>\n<LAND_GBN_NM>대지</LAND_GBN_NM>\n<BOBN>0144</BOBN>\n<BUBN>0019</BUBN>\n<FLR_NO>9</FLR_NO>\n<CNTRCT_DE>20240325</CNTRCT_DE>\n<RENT_GBN>전세</RENT_GBN>\n<RENT_AREA>21.37</RENT_AREA>\n<RENT_GTN>23600</RENT_GTN>\n<RENT_FEE>0</RENT_FEE>\n<BLDG_NM>킹캐슬8차</BLDG_NM>\n<BUILD_YEAR>2024</BUILD_YEAR>\n<HOUSE_GBN_NM>오피스텔</HOUSE_GBN_NM>\n<CNTRCT_PRD>24.04~26.04</CNTRCT_PRD>\n<NEW_RON_SECD>신규</NEW_RON_SECD>\n<CNTRCT_UPDT_RQEST_AT/>\n<BEFORE_GRNTY_AMOUNT/>\n<BEFORE_MT_RENT_CHRGE/>\n</row>\n<row>\n<ACC_YEAR>2024</ACC_YEAR>\n<SGG_CD>11470</SGG_CD>\n<SGG_NM>양천구</SGG_NM>\n<BJDONG_CD>10100</BJDONG_CD>\n<BJDONG_NM>신정동</BJDONG_NM>\n<LAND_GBN>1</LAND_GBN>\n<LAND_GBN_NM>대지</LAND_GBN_NM>\n<BOBN>1182</BOBN>\n<BUBN>0015</BUBN>\n<FLR_NO>5</FLR_NO>\n<CNTRCT_DE>20240325</CNTRCT_DE>\n<RENT_GBN>전세</RENT_GBN>\n<RENT_AREA>23.31</RENT_AREA>\n<RENT_GTN>21200</RENT_GTN>\n<RENT_FEE>0</RENT_FEE>\n<BLDG_NM>보스코 빌딩</BLDG_NM>\n<BUILD_YEAR>2020</BUILD_YEAR>\n<HOUSE_GBN_NM>오피스텔</HOUSE_GBN_NM>\n<CNTRCT_PRD>24.04~26.04</CNTRCT_PRD>\n<NEW_RON_SECD>신규</NEW_RON_SECD>\n<CNTRCT_UPDT_RQEST_AT/>\n<BEFORE_GRNTY_AMOUNT/>\n<BEFORE_MT_RENT_CHRGE/>\n</row>\n<row>\n<ACC_YEAR>2024</ACC_YEAR>\n<SGG_CD>11230</SGG_CD>\n<SGG_NM>동대문구</SGG_NM>\n<BJDONG_CD>10400</BJDONG_CD>\n<BJDONG_NM>전농동</BJDONG_NM>\n<LAND_GBN>1</LAND_GBN>\n<LAND_GBN_NM>대지</LAND_GBN_NM>\n<BOBN>0620</BOBN>\n<BUBN>0071</BUBN>\n<FLR_NO>10</FLR_NO>\n<CNTRCT_DE>20240325</CNTRCT_DE>\n<RENT_GBN>월세</RENT_GBN>\n<RENT_AREA>43.44</RENT_AREA>\n<RENT_GTN>3000</RENT_GTN>\n<RENT_FEE>150</RENT_FEE>\n<BLDG_NM>청량리더블유디세븐스</BLDG_NM>\n<BUILD_YEAR>2023</BUILD_YEAR>\n<HOUSE_GBN_NM>오피스텔</HOUSE_GBN_NM>\n<CNTRCT_PRD>24.04~25.04</CNTRCT_PRD>\n<NEW_RON_SECD>신규</NEW_RON_SECD>\n<CNTRCT_UPDT_RQEST_AT/>\n<BEFORE_GRNTY_AMOUNT/>\n<BEFORE_MT_RENT_CHRGE/>\n</row>\n</tbLnOpendataRentV>\n'

In [8]:
#강의 때 배운 파라미터 방식으로 안 됨. url에 년도 입력하니 해결

import requests

url = 'http://openapi.seoul.go.kr:8088/4178724f416e656437366d46676961/xml/tbLnOpendataRentV/1/5/'

# 파라미터를 딕셔너리 형태로 입력 : 강의 때 들은 방식(소괄호 사용)으로는 에러나서 불가능 했음(ValueError: too many values to unpack (expected 2))
params = {
    'KEY': '4178724f416e656437366d46676961',
    'TYPE': 'xml',
    'SERVICE': 'tbLnOpendataRentV',
    'START_INDEX': 0,
    'END_INDEX': 100,
    'ACC_YEAR': '2024',   # 접수연도
}

response = requests.get(url, params)
response.text

'<?xml version="1.0" encoding="UTF-8"?>\n<tbLnOpendataRentV>\n<list_total_count>5806962</list_total_count>\n<RESULT>\n<CODE>INFO-000</CODE>\n<MESSAGE>정상 처리되었습니다</MESSAGE>\n</RESULT>\n<row>\n<ACC_YEAR>2024</ACC_YEAR>\n<SGG_CD>11290</SGG_CD>\n<SGG_NM>성북구</SGG_NM>\n<BJDONG_CD>10300</BJDONG_CD>\n<BJDONG_NM>돈암동</BJDONG_NM>\n<LAND_GBN>1</LAND_GBN>\n<LAND_GBN_NM>대지</LAND_GBN_NM>\n<BOBN>0524</BOBN>\n<BUBN>0000</BUBN>\n<FLR_NO>6</FLR_NO>\n<CNTRCT_DE>20240327</CNTRCT_DE>\n<RENT_GBN>전세</RENT_GBN>\n<RENT_AREA>84.98</RENT_AREA>\n<RENT_GTN>50000</RENT_GTN>\n<RENT_FEE>0</RENT_FEE>\n<BLDG_NM>일신건영휴먼빌아파트</BLDG_NM>\n<BUILD_YEAR>2005</BUILD_YEAR>\n<HOUSE_GBN_NM>아파트</HOUSE_GBN_NM>\n<CNTRCT_PRD>24.02~24.09</CNTRCT_PRD>\n<NEW_RON_SECD>갱신</NEW_RON_SECD>\n<CNTRCT_UPDT_RQEST_AT/>\n<BEFORE_GRNTY_AMOUNT>600000000</BEFORE_GRNTY_AMOUNT>\n<BEFORE_MT_RENT_CHRGE/>\n</row>\n<row>\n<ACC_YEAR>2024</ACC_YEAR>\n<SGG_CD>11650</SGG_CD>\n<SGG_NM>서초구</SGG_NM>\n<BJDONG_CD>10300</BJDONG_CD>\n<BJDONG_NM>우면동</BJDONG_NM>\n<LAND_GBN>1</LAND_GBN>\n<LAND_GBN_NM>대지</LAND_GBN_NM>\n<BOBN>0070</BOBN>\n<BUBN>0000</BUBN>\n<FLR_NO>2</FLR_NO>\n<CNTRCT_DE>20240327</CNTRCT_DE>\n<RENT_GBN>전세</RENT_GBN>\n<RENT_AREA>52.47</RENT_AREA>\n<RENT_GTN>45000</RENT_GTN>\n<RENT_FEE>0</RENT_FEE>\n<BLDG_NM>코오롱</BLDG_NM>\n<BUILD_YEAR>1994</BUILD_YEAR>\n<HOUSE_GBN_NM>아파트</HOUSE_GBN_NM>\n<CNTRCT_PRD>24.04~26.04</CNTRCT_PRD>\n<NEW_RON_SECD>신규</NEW_RON_SECD>\n<CNTRCT_UPDT_RQEST_AT/>\n<BEFORE_GRNTY_AMOUNT/>\n<BEFORE_MT_RENT_CHRGE/>\n</row>\n<row>\n<ACC_YEAR>2024</ACC_YEAR>\n<SGG_CD>11620</SGG_CD>\n<SGG_NM>관악구</SGG_NM>\n<BJDONG_CD>10100</BJDONG_CD>\n<BJDONG_NM>봉천동</BJDONG_NM>\n<LAND_GBN>1</LAND_GBN>\n<LAND_GBN_NM>대지</LAND_GBN_NM>\n<BOBN>1712</BOBN>\n<BUBN>0000</BUBN>\n<FLR_NO>23</FLR_NO>\n<CNTRCT_DE>20240327</CNTRCT_DE>\n<RENT_GBN>월세</RENT_GBN>\n<RENT_AREA>84.96</RENT_AREA>\n<RENT_GTN>45000</RENT_GTN>\n<RENT_FEE>15</RENT_FEE>\n<BLDG_NM>관악드림(동아)</BLDG_NM>\n<BUILD_YEAR>2003</BUILD_YEAR>\n<HOUSE_GBN_NM>아파트</HOUSE_GBN_NM>\n<CNTRCT_PRD>24.04~26.04</CNTRCT_PRD>\n<NEW_RON_SECD>갱신</NEW_RON_SECD>\n<CNTRCT_UPDT_RQEST_AT/>\n<BEFORE_GRNTY_AMOUNT>430000000</BEFORE_GRNTY_AMOUNT>\n<BEFORE_MT_RENT_CHRGE>50000</BEFORE_MT_RENT_CHRGE>\n</row>\n<row>\n<ACC_YEAR>2024</ACC_YEAR>\n<SGG_CD>11710</SGG_CD>\n<SGG_NM>송파구</SGG_NM>\n<BJDONG_CD>10200</BJDONG_CD>\n<BJDONG_NM>신천동</BJDONG_NM>\n<LAND_GBN>1</LAND_GBN>\n<LAND_GBN_NM>대지</LAND_GBN_NM>\n<BOBN>0007</BOBN>\n<BUBN>0000</BUBN>\n<FLR_NO>1</FLR_NO>\n<CNTRCT_DE>20240327</CNTRCT_DE>\n<RENT_GBN>전세</RENT_GBN>\n<RENT_AREA>82.45</RENT_AREA>\n<RENT_GTN>60100</RENT_GTN>\n<RENT_FEE>0</RENT_FEE>\n<BLDG_NM>장미1</BLDG_NM>\n<BUILD_YEAR>1979</BUILD_YEAR>\n<HOUSE_GBN_NM>아파트</HOUSE_GBN_NM>\n<CNTRCT_PRD>24.04~26.04</CNTRCT_PRD>\n<NEW_RON_SECD>갱신</NEW_RON_SECD>\n<CNTRCT_UPDT_RQEST_AT>○</CNTRCT_UPDT_RQEST_AT>\n<BEFORE_GRNTY_AMOUNT>600000000</BEFORE_GRNTY_AMOUNT>\n<BEFORE_MT_RENT_CHRGE/>\n</row>\n<row>\n<ACC_YEAR>2024</ACC_YEAR>\n<SGG_CD>11230</SGG_CD>\n<SGG_NM>동대문구</SGG_NM>\n<BJDONG_CD>10600</BJDONG_CD>\n<BJDONG_NM>장안동</BJDONG_NM>\n<LAND_GBN>1</LAND_GBN>\n<LAND_GBN_NM>대지</LAND_GBN_NM>\n<BOBN>0571</BOBN>\n<BUBN>0000</BUBN>\n<FLR_NO>8</FLR_NO>\n<CNTRCT_DE>20240327</CNTRCT_DE>\n<RENT_GBN>전세</RENT_GBN>\n<RENT_AREA>84.3</RENT_AREA>\n<RENT_GTN>48100</RENT_GTN>\n<RENT_FEE>0</RENT_FEE>\n<BLDG_NM>현대홈타운3차</BLDG_NM>\n<BUILD_YEAR>2006</BUILD_YEAR>\n<HOUSE_GBN_NM>아파트</HOUSE_GBN_NM>\n<CNTRCT_PRD>24.05~26.05</CNTRCT_PRD>\n<NEW_RON_SECD>갱신</NEW_RON_SECD>\n<CNTRCT_UPDT_RQEST_AT/>\n<BEFORE_GRNTY_AMOUNT>441000000</BEFORE_GRNTY_AMOUNT>\n<BEFORE_MT_RENT_CHRGE/>\n</row>\n</tbLnOpendataRentV>\n'

In [9]:
#fromstring 메소드를 통해 XML 자료형을 처리할 수 있음
ET.fromstring(response.text)

In [10]:
#강의 때 들은 방식으로X

root = ET.fromstring(response.text)
row_dict = {'ACC_YEAR':[],'SGG_CD':[],'SGG_NM':[],'BJDONG_CD':[],'BJDONG_NM':[],'LAND_GBN':[],
'LAND_GBN_NM':[],'BOBN':[],'BUBN':[],'FLR_NO':[],'CNTRCT_DE':[],'RENT_GBN':[],'RENT_AREA':[],'RENT_GTN':[],'RENT_FEE':[],'BLDG_NM':[],'BUILD_YEAR':[]
,'HOUSE_GBN_NM':[],'CNTRCT_PRD':[],'NEW_RON_SECD':[],'CNTRCT_UPDT_RQEST_AT':[],'BEFORE_GRNTY_AMOUNT':[],'BEFORE_MT_RENT_CHRGE':[]}
#data/item 계층 밑의 값을 list으로 가져와 iteration
for i in root.findall('./data/row'):
    # ROW로부터 텍스트를 가져와 딕셔너리에 저장
    for j in i:
        row_dict[j.tag].append(j.text)
df = pd.DataFrame(row_dict)
df.head()


#정규형 2형 만족X : kind_name에 두가지 종류
#dpr1 문자형

Empty DataFrame
Columns: [ACC_YEAR, SGG_CD, SGG_NM, BJDONG_CD, BJDONG_NM, LAND_GBN, LAND_GBN_NM, BOBN, BUBN, FLR_NO, CNTRCT_DE, RENT_GBN, RENT_AREA, RENT_GTN, RENT_FEE, BLDG_NM, BUILD_YEAR, HOUSE_GBN_NM, CNTRCT_PRD, NEW_RON_SECD, CNTRCT_UPDT_RQEST_AT, BEFORE_GRNTY_AMOUNT, BEFORE_MT_RENT_CHRGE]
Index: []

[0 rows x 23 columns]

In [11]:
import pandas as pd

# XML을 DataFrame으로 변환
df = pd.read_xml(response.text)

# 필요한 컬럼 선택
columns_to_keep = ['ACC_YEAR', 'SGG_CD', 'SGG_NM', 'BJDONG_CD', 'BJDONG_NM', 'LAND_GBN', 'LAND_GBN_NM', 'BOBN', 'BUBN', 'FLR_NO', 'CNTRCT_DE', 'RENT_GBN', 'RENT_AREA', 'RENT_GTN', 'RENT_FEE', 'BLDG_NM', 'BUILD_YEAR', 'HOUSE_GBN_NM', 'CNTRCT_PRD', 'NEW_RON_SECD', 'CNTRCT_UPDT_RQEST_AT', 'BEFORE_GRNTY_AMOUNT', 'BEFORE_MT_RENT_CHRGE']
df = df[columns_to_keep]

# 결과 확인
usefull = ['ACC_YEAR', 'SGG_CD', 'SGG_NM', 'BJDONG_NM', 'FLR_NO', 'CNTRCT_DE', 'RENT_GBN', 'RENT_AREA', 'RENT_FEE', 'BLDG_NM','BUILD_YEAR', 'HOUSE_GBN_NM']
df[usefull].head(20)

,ACC_YEAR,SGG_CD,SGG_NM,BJDONG_NM,FLR_NO,CNTRCT_DE,RENT_GBN,RENT_AREA,RENT_FEE,BLDG_NM,BUILD_YEAR,HOUSE_GBN_NM
0,NaN,NaN,None,None,NaN,NaN,None,NaN,NaN,None,NaN,None
1,NaN,NaN,None,None,NaN,NaN,None,NaN,NaN,None,NaN,None
2,2024.0,11290.0,성북구,돈암동,6.0,20240327.0,전세,84.98,0.0,일신건영휴먼빌아파트,2005.0,아파트
3,2024.0,11650.0,서초구,우면동,2.0,20240327.0,전세,52.47,0.0,코오롱,1994.0,아파트
4,2024.0,11620.0,관악구,봉천동,23.0,20240327.0,월세,84.96,15.0,관악드림(동아),2003.0,아파트
5,2024.0,11710.0,송파구,신천동,1.0,20240327.0,전세,82.45,0.0,장미1,1979.0,아파트
6,2024.0,11230.0,동대문구,장안동,8.0,20240327.0,전세,84.30,0.0,현대홈타운3차,2006.0,아파트

In [ ]:
#깃허브 코드 복사
#리눅스 명령어
!git clone 'https://github.com/bellepoque7/whereisplanb.git'

Cloning into 'whereisplanb'...
remote: Enumerating objects: 944, done.
remote: Counting objects: 100% (317/317), done.
remote: Compressing objects: 100% (230/230), done.
remote: Total 944 (delta 131), reused 252 (delta 78), pack-reused 627
Receiving objects: 100% (944/944), 2.95 MiB | 14.94 MiB/s, done.
Resolving deltas: 100% (176/176), done.